[STEP 1] songmani
tasty-code/ios-baseball pull request #12
Opened 2022-08-10 02:33 UTC by seunghui5247

@jaemuYeo 리뷰 부탁드립니다

**[STEP 1] 기능**

- 랜덤값 생성 함수
- 스트라이크 볼 결과 반환 함수
- 게임시작 함수
- Flow Chart 추가

**고민되었던 점**
`
while checkNumber.count < 3 {
        let number = Int.random(in: 1...9)
        if checkNumber.contains(number) {
            continue
        } else {
            checkNumber.append(number)
        }
    }
`
랜덤값을 생성할 때 중복되는 값이 나온 것이 고민되었다
만약 새로운 랜덤값이 포함되어 있다면 다시 랜덤값을 생성하고 그렇지 않다면 array에 값을 추가하는 방법으로 해결하였다

2022-08-10 03:39 UTC, jaemuYeo requested changes
송마니 첫 번째 PR 고생하셨습니다!! 👏
제가 남기는 코멘트는 '전부 고쳐라!!' 라는 의미보다는
정말로 궁금해서 이유에 대해 물어보는 것도 있고,
제 의견에 반대 의견이 있다면 그 이유에 대해 말씀해주셔도 좋습니다 😀
너무 많은 코멘트가 달리더라도 의기소침하지 않고
차근차근 고민해보시면 좋을 거 같아요!! 화이팅입니다 !! 💪

## 순서도
전체적으로 많은 부분이 생략되었다는 느낌을 받았어요 🤔
좀 더 작게 쪼개서 정말로 하나하나 다 표현해보면 어떨까요?
바로 작성하기 힘들다면 공책에 수기로 적어본 후에 순서도를 그려나가도 좋은 방법입니다!🔥
예를들면
1. 게임을 종료하는 것은 있는데 게임을 시작하는 표현 없음
2. 1 또는 2 이외의 값을 입력했는데 거기에 대한 처리가 빠짐
3. 임의의 수랑 스트라이크, 볼 등을 출력하는 부분

그 외에도 더 고민해보면 좋을 거같아요 😀

## 코드
코드에 대한 부분은 코드에 코멘트로 남겨놓겠습니다!
스텝1에는 없는 실행예시가 보이는군요 👀

2022-08-10 03:39 UTC, jaemuYeo commented on baseball/baseball/main.swift
> +var checkNumber:[Int] = []
numbers는 복수형으로 네이밍 해주었는데 여기는 안되있네요!?

2022-08-10 03:39 UTC, jaemuYeo commented on baseball/baseball/main.swift
> +var chance: Int = 9
찬스는 무슨 찬스인가요? 네이밍이 명확하지 않은거 같아요 🤔

2022-08-10 03:39 UTC, jaemuYeo commented on baseball/baseball/main.swift
> +func strikeBallCheck() {
swift 네이밍가이드에서 함수의 네이밍은 어떻게 작성하라고 되어있나요??
힌트는 위에 함수는 잘하셨어요 😀

2022-08-10 03:39 UTC, jaemuYeo commented on baseball/baseball/main.swift
> +func makeRandomNumber() {
현재 구현하신 부분(== 고민한 부분)은 Array 타입으로 값을 담아서
중복된 값을 체크하며 배열에 담고계신거같아요!
이렇게 비교하지 않고 중복된 값을 필터해주는 Swift Collection Type이 있는데
한 번 조사해보고 수정해보시면 코드가 간결해질 것 같습니다 😄

2022-08-10 03:39 UTC, jaemuYeo commented on baseball/baseball/main.swift
> +func gameStart() {
여기도 네이밍 확인 부탁해요~

2022-08-10 03:39 UTC, jaemuYeo commented on baseball/baseball/main.swift
> +    let menu = Int(readLine()!)!
프로젝트 기술요구사항을 읽어보시면 `이번 과제 수행시 제약사항`이라는 부분이 있어요
첫 세션에서 옵셔널에 대해 배웠고 강제추출에 대한 단점과 옵셔널 바인딩을 학습했는데
활용해 볼 수 있을까요?

이 부분은 스텝2 내용이라 다음 스텝에서 수정해주셔도 됩니다!

2022-08-10 03:39 UTC, jaemuYeo commented on baseball/baseball/main.swift
> +gameMenu()
네이밍만 봐서는 gameStart()가 더 적절할 거같은데
gameMenu를 통해 게임을 시작하네요!

2022-08-10 03:39 UTC, jaemuYeo commented on baseball/baseball/main.swift
> +        while numbers.count < 3 {
프로젝트 기술요구사항 `이번 과제 수행시 제약사항`에서 '들여쓰기는 2번을 초과하지 않습니다'라고 적혀있습니다🤔
이런 제약이 나온 이유가 무엇일까요??

2022-08-10 09:41 UTC, jaemuYeo requested changes
빠르게 수정해주셨군요!! 고생많았어요 ☺️
순서도도 많이 고민한티가 납니다!👍
다만
<img width="680" alt="스크린샷 2022-08-10 오후 5 42 13" src="https://user-images.githubusercontent.com/70311145/183858343-47b6070d-f392-4464-8934-3659e2117878.png">
요 친구들에 대한 입력 에러처리도 필요할거 같아요 🤔

코드는 네이밍에 대한 부분은 많이 개선되었어요!! 너무 좋아요 👍
다만 지금 코드를 실행했을 때 프로젝트의 실행예시와 다른 부분(빠진 부분)이 있습니다!
추가적으로 구현해주시면 좋을 거 같아요 ~

2022-08-10 09:41 UTC, jaemuYeo commented on baseball/baseball/main.swift
> +var randomNumber: Set<Int> = []
한 곳에서만 사용된다면 전역변수보다는 지역변수가 좋을 거 같아요!
전역변수와 지역변수의 차이점과 장단점에 대해 알아보면 좋을 것 같아요 😀

2022-08-10 09:41 UTC, jaemuYeo commented on baseball/baseball/main.swift
> +        while userNumbers.count < 3 {
여기서 while문이 중첩되어 사용되고 있네요!!
어떻게 개선하면 중첩되지않게 구현할 수 있을까요?
중첩을 하지 않는 이유에 대해서도 생각을 적어주시면 좋을거같아요 😁

2022-08-11 00:43 UTC, cjstmdgml commented on baseball/baseball/main.swift
> +        while userNumbers.count < 3 {
while문을 중첩해서 사용하게 되면 수행시간이 오래 걸리는 문제가 발생할 수 있기 때문에 중첩을 하지 않는것 같아요

2022-08-11 00:44 UTC, seunghui5247 commented on baseball/baseball/main.swift
> +        while userNumbers.count < 3 {
while문을 중첩해서 사용하게 되면 수행시간이 오래 걸리는 문제가 발생할 수 있기 때문에 중첩을 하지 않는것 같아요

2022-08-11 09:41 UTC, jaemuYeo requested changes
중첩에 대한 부분을 잘 해결해주었군요!
다만 그 외의 코멘트에 대한 부분은 아직 수정이 안된것같아요
제일 중요한 `실행 예시`와의 결과가 다릅니다!!
꼼꼼히 살펴보고 다시 구현부탁해요 ☺️

2022-08-12 03:06 UTC, jaemuYeo reviewed
스텝1 고생많았어요 송마니!👏
이번 스텝은 여기서 머지 진행하겠습니다~
스텝2를 수행할 때에는 함수 하나가 몇 가지 일을 하고있는지 파악해보고
함수 하나에 하나의 기능을 담당하도록 분리해볼 수 있도록 시도해보세요!!

2022-08-12 03:07 UTC, merged