[STEP 1] cu
tasty-code/ios-baseball pull request #14
Opened 2022-08-10 03:08 UTC by Schro2109

@jaemuYeo 
# [STEP 1] 수행 내용
1. 순서도 작성
2. 중복되지 않은 임의의 수 3개를 생성해 정수타입 배열로 반환하는 함수 getRandomNumbers() 작성
3. 컴퓨터가 생성한 난수들과 플레이어의 난수들을 비교해 스트라이크, 볼의 결과를 출력하는 함수 compare() 작성
4. 게임 시작 함수 gameStart() 작성

# 고민 되었던 점
전역 변수인 maxChance(시도횟수)를 게임 시작 함수에 어떻게 전달할지, 또한 게임 시작 함수를 여러번 호출할 때
시도횟수를 어떻게 초기화 할지 고민되었으나 maxChance를 상수 9로 설정하고 게임 시작 함수 실행 시 maxChance의 값을 가져와 사용하는 방식을 활용하여 해결했습니다.
```
let maxChance: Int = 9
gameStart()

func gameStart() {
    var chance = maxChance
    ...
```

2022-08-10 06:56 UTC, jaemuYeo requested changes
씨유!! 프로젝트 첫 PR 하느라 고생하셨어요👍👏
README에 이미지 넣기로 구글링하시면 여러 방법이 나올거예요!!
캡처 후 드래그해서 넣어도 된답니다 ㅎㅎ
제가 앞으로 남겨놓을 코멘트들은 100% 정답을 요구하는 것이아니라
저의 의견을 말하고 씨유의 코드에 대한 이유를 듣고 싶어서입니다!!
코멘트에 대한 모든 것을 수정할 필요는 없으니
반대되는 생각이 있다면 그 이유를 남겨주시고 언제든 질문 환영합니다!! 😄

## 순서도
1. 게임 패배 메시지를 띄운 후 `프로그램이 시작한다`로 가는 것이 좋을 것 같은데 씨유는 어떻게 생각해요?
2. 입력 숫자 0, 1이외에의 값은 에러 처리를 했는데 사용자가 입력하는 부분에서는 에러 처리를 안했군요!
3. count를 1 빼고나서 count가 1 이상인지를 판단하는 것은 어떤가요?
4. 게임 슬리 메시지를 띄운 뒤에 향하는 흐름선의 위치가 맞지 않다 생각해요!!

그 외에는 색깔도 입히고 너무 깔끔하게 잘 작성하셨네요 멋져요!! 👍

## 코드
코드에 대한 부분은 개별 코드에 코멘트로 남기겠습니다!

2022-08-10 06:56 UTC, jaemuYeo commented on CU-iOS Baseball/CU-iOS Baseball/main.swift
> +gameStart()
게임 실행 함수를 맨 위에 올린 이유가 있나요??

2022-08-10 06:56 UTC, jaemuYeo commented on CU-iOS Baseball/CU-iOS Baseball/main.swift
> +func gameStart() {
[이 곳](https://www.swift.org/documentation/api-design-guidelines/)의 네이밍 부분에서 함수의 네이밍은 어떻게 하면 좋은지에 대해 한 번 더 읽어보면 좋을 거 같습니다 ☺️

2022-08-10 06:56 UTC, jaemuYeo commented on CU-iOS Baseball/CU-iOS Baseball/main.swift
> +    var chance = maxChance
전역변수 maxChance를 상수로 하신 이유가 궁금해요!
변수였다면 굳이 변수를 새로만들어 할당할 이유는 없었을 거 같은걸요??
그리고 해당 전역변수는 현재 이 함수에서만 사용하고 있는데
지역변수로 두지 않은 이유도 궁금합니다~

2022-08-10 06:56 UTC, jaemuYeo commented on CU-iOS Baseball/CU-iOS Baseball/main.swift
> +        print("임의의 수 : \(userRandomNumbers[0]), \(userRandomNumbers[1]), \(userRandomNumbers[2])")
실행 예시와 다르게 출력되고 있어요🤔

2022-08-10 06:56 UTC, jaemuYeo commented on CU-iOS Baseball/CU-iOS Baseball/main.swift
> +        chance = chance - 1
현재 이 수식을 간단하게 표현하는 방법이 있습니다!
[Basic Operators](https://docs.swift.org/swift-book/LanguageGuide/BasicOperators.html)문서를 읽어보고 적용해보세요 :)

2022-08-10 06:56 UTC, jaemuYeo commented on CU-iOS Baseball/CU-iOS Baseball/main.swift
> +    let gameRandomNumbers = getRandomNumbers()
이렇게 컬렉션타입에 대한 것을 복수형으로 네이밍 해주신것은 너무 잘하셨네요!! 최곱니다 👍

2022-08-10 06:56 UTC, jaemuYeo commented on CU-iOS Baseball/CU-iOS Baseball/main.swift
> +    var arr: [Int] = []
위 함수의 while문과 변수는 개행을 진행하였는데
이 곳은 안하셨군요!!
생성한 변수가 사용되는 Control Flow는 개행을 안하고 작성하시는 편인가요??
씨유의 코드 스타일이라면 참고하겠습니다 😉

2022-08-10 06:56 UTC, jaemuYeo commented on CU-iOS Baseball/CU-iOS Baseball/main.swift
> +func getRandomNumbers() -> [Int] {
이 함수를 통해 Array 타입으로 세 개의 중복되지 않은 값을 구현하였군요!
Swift Collection 타입중에는 중복되지 않는 차집합의 값들만 넣을 수 있는 컬렉션 타입이 존재해요!
문서를 읽어보고 적용해보시면 훨씬 간결하게 코드가 수정될 거 같아요! Try!! 💪

2022-08-10 06:56 UTC, jaemuYeo commented on CU-iOS Baseball/CU-iOS Baseball/main.swift
> +func compare(_ gameRandomNumbers: [Int], and: [Int]) -> String{
중괄호의 띄어쓰기 실수가 있군요!! 

저는 이 함수의 네이밍이 모호하다 생각이 들어요! 무엇과 비교하는지가 명확하지 않은 거 같습니다
```swift
compare(_ gameRandomNumbers: [Int], and userNumbers: [Int]) -> String {}
```
와 같은 네이밍은 어떻게 생각하세요??

2022-08-10 06:56 UTC, jaemuYeo commented on CU-iOS Baseball/CU-iOS Baseball/main.swift
> +    }else {
띄어쓰기 실수가 있습니다!

2022-08-10 06:56 UTC, jaemuYeo commented on CU-iOS Baseball/CU-iOS Baseball/main.swift
> +
if문과 else문에 개행은 하지 않아도 될거같아요~

2022-08-10 08:13 UTC, Schro2109 commented on CU-iOS Baseball/CU-iOS Baseball/main.swift
> +gameStart()
가장 먼저 호출되는게 게임 실행 함수라서 맨 위에 올리게 되었습니다!

2022-08-10 08:14 UTC, Schro2109 commented on CU-iOS Baseball/CU-iOS Baseball/main.swift
> +    var chance = maxChance
코드 작성시에는 미처 생각하지 못한 부분이었던 것 같습니다.. 이후 수정하겠습니다!

2022-08-10 08:25 UTC, Schro2109 commented on CU-iOS Baseball/CU-iOS Baseball/main.swift
> +func gameStart() {
넵 읽어보고 고쳐보겠습니다

2022-08-10 08:25 UTC, Schro2109 commented on CU-iOS Baseball/CU-iOS Baseball/main.swift
> +        print("임의의 수 : \(userRandomNumbers[0]), \(userRandomNumbers[1]), \(userRandomNumbers[2])")
앗 확인해보니 다른 부분이 있었네요 바로 수정하겠습니다

2022-08-10 08:25 UTC, Schro2109 commented on CU-iOS Baseball/CU-iOS Baseball/main.swift
> +        chance = chance - 1
넵 확인하고 적용해보겠습니다!

2022-08-10 08:37 UTC, Schro2109 commented on CU-iOS Baseball/CU-iOS Baseball/main.swift
> +func getRandomNumbers() -> [Int] {
넵 Set타입으로 한번 바꿔보겠습니다

2022-08-10 08:40 UTC, Schro2109 commented on CU-iOS Baseball/CU-iOS Baseball/main.swift
> +    }else {
넵 수정하겠습니다!

2022-08-11 00:25 UTC, Schro2109 commented on CU-iOS Baseball/CU-iOS Baseball/main.swift
> +    var arr: [Int] = []
관련있는 변수와는 붙여야겠다고 생각했는데 다시 보니 개행을 하는 것이 가독성에 더 도움이 될 것 같습니다!

2022-08-11 00:37 UTC, Schro2109 commented on CU-iOS Baseball/CU-iOS Baseball/main.swift
> +
넵 수정했습니다!

2022-08-11 01:04 UTC, Schro2109 commented on CU-iOS Baseball/CU-iOS Baseball/main.swift
> +func compare(_ gameRandomNumbers: [Int], and: [Int]) -> String{
함수를 저렇게 작성할 수 있는지는 처음 알았네요..!
수정해보겠습니다!

2022-08-11 03:19 UTC, Schro2109 commented on CU-iOS Baseball/CU-iOS Baseball/main.swift
> +    let gameRandomNumbers = getRandomNumbers()
감사합니다!

2022-08-11 05:46 UTC, jaemuYeo reviewed
재수정도 빠르게 하셨군요!!
두 번째이니 수정된 부분 위주로 볼게요~

## 순서도
<img width="315" alt="스크린샷 2022-08-11 오후 2 29 14" src="https://user-images.githubusercontent.com/70311145/184069768-b8dc71de-8772-42e3-b4a4-acecc001c8b3.png">
전체적으로 너무 잘 수정해주셨어요!! 멋집니다 👍
이 순서도를 바탕으로 이번 프로젝트 스텝2까지 마무리하고
코드와 순서도를 비교해보며 같은 흐름을 가지고 있는지
비교해봐도 좋은 경험이 될거예요 😀
다만 저기 이미지 처럼 흐름선이 끊긴 부분은 실수한걸로 생각할게요 !! ㅎㅎ

## 코드
전체적으로 불필요한 개행이 너무 많은 거 같아요!
본인만의 스타일도 있지만 평균적으로 정해진(?) 정도의 컨벤션이 있으니
이건 차차 많은 사람들의 코드를 보면서 개선하면 좋을 거 같습니다 ㅎㅎ

스텝1은 이쯤하고 제가 코멘트 남겨놓은 부분만 수정할 부분 있으면 진행후에
스텝2 진행하시면 되겠습니다!!
`머지` 진행할게요~

2022-08-11 05:46 UTC, jaemuYeo commented on CU-iOS Baseball/CU-iOS Baseball/main.swift
> +func startingGame() {
start만으로도 '시작하다'라는 동사적 의미를 가지고 있어
꼭 ing를 붙이지 않아도 될거같아요!

2022-08-11 05:46 UTC, jaemuYeo commented on CU-iOS Baseball/CU-iOS Baseball/main.swift
> +
이 곳은 불필요한 개행이라 생각합니다!

2022-08-11 05:46 UTC, jaemuYeo commented on CU-iOS Baseball/CU-iOS Baseball/main.swift
> +startingGame()
함수 호출은 가장 아래에서 해주면 좋을 것 같아요!
그 이유에 대해 생각해보면 좋겠어요 😀

2022-08-11 05:46 UTC, jaemuYeo commented on CU-iOS Baseball/CU-iOS Baseball/main.swift
> +func compare(_ gameRandomNumbers: [Int], and userNumbers: [Int]) -> String {
오 !! 이제는 함수의 뜻을 더 명확하게 알 수 있을 거 같아요 👍

2022-08-11 05:46 UTC, merged

2022-08-12 00:24 UTC, Schro2109 commented on CU-iOS Baseball/CU-iOS Baseball/main.swift
> +func startingGame() {
넵!

2022-08-12 00:25 UTC, Schro2109 commented on CU-iOS Baseball/CU-iOS Baseball/main.swift
> +startingGame()
넵 수정하겠습니다

2022-08-12 00:25 UTC, Schro2109 commented on CU-iOS Baseball/CU-iOS Baseball/main.swift
> +func compare(_ gameRandomNumbers: [Int], and userNumbers: [Int]) -> String {
감사합니다!

2022-08-12 00:28 UTC, Schro2109 commented on CU-iOS Baseball/CU-iOS Baseball/main.swift
> +
수정해보겠습니다!