[STEP1] JaeGeun
tasty-code/ios-baseball pull request #15
Opened 2022-08-10 03:14 UTC by wormsJJG

@jaemuYeo  리뷰 부탁드립니다.

# 수행내용
임의의 수와 컴퓨터의 수를  1~9까지중 중복이 되지않는 3개의 수를 배열에 담아 생성
두 배열을 비교 후 판정
게임을 한판 진행한 후 판정이 끝나면 카운트 차감
# 고민한 내용
컴퓨터와 사용자가 입력하는 값들을 중복되지 않게 하기위해 고민했습니다.
하지만 swift의 배열 기본 함수들을 사용하여 해결하였습니다.
# 아쉬웠던 점
완성을 다하고 step1을 위해 수정한 코드라 지저분한게 아숴웠습니다.
역시 모든 잘 읽고 잘 생각하고 하는게 최고인것 같습니다..
다음 프로젝트에서는 더 신경써서 임해야 겠습니다.

2022-08-10 05:52 UTC, jaemuYeo requested changes
재근!! 여러 문제때문에 꼬였는데 그래도 PR 보내신다고 고생많았습니다 👏
브랜치를 나누면서 Step1에는 Flow Chart가 사라졌네요 ㅠ_ㅠ
PR 재요청때 넣어주시거나 아니면 Step2에 한 번에보도록 할게요!!
코드에 대한 코멘트는 해당 코드에 달아두겠습니다 🔥

제가 단 코멘트는 100% 정답이 아니고
재근의 코드에 대한 이유가 궁금한 부분도 있고,
조금 더 좋은 방향을 제시하는 것 뿐이니 
저와 반대의 의견이 있거나 맞다 생각하시는 부분은 그 이유에 대해 설명부탁해요🙏
너무 많은 코멘트가 달릴경우에도 의기소침하지 않길 바라요!!

실행예시와 맞지 않는 결과가 나와서 이미지 첨부할게요!
어디가 문제일지 고민해보고 해결이 안된다면 언제든 질문주세요~~
<img width="142" alt="스크린샷 2022-08-10 오후 2 36 04" src="https://user-images.githubusercontent.com/70311145/183823662-cbb599e2-b2db-4eec-8a41-420ebac2732f.png">

2022-08-10 05:52 UTC, jaemuYeo commented on ios-baseball/ios-baseball/main.swift
> +var menuNum: Int = 0
화요일 세션에서 훑어봤던 Swift Style 가이드 문서에서 네이밍을 축약하는 것을 추천하지 않고 있어요!
기억하시나요?
arr -> array, num -> number 와 같이 명확한 네이밍으로 습관들이도록 노력해보세요😊

2022-08-10 05:52 UTC, jaemuYeo commented on ios-baseball/ios-baseball/main.swift
> +var leftCnt: Int = 9
이 네이밍 또한 저는 무엇을 뜻하는지 모르겠어요! 🤔

2022-08-10 05:52 UTC, jaemuYeo commented on ios-baseball/ios-baseball/main.swift
> +func startMenu() {
Step2에 해당하는 내용이니 스텝2 진행할때 수정 부탁드립니다! (네이밍도 고려해보세요)

2022-08-10 05:52 UTC, jaemuYeo commented on ios-baseball/ios-baseball/main.swift
> +    menuNum = Int(readLine()!)!
프로젝트 요구사항 페이지의 `제약 사항`을 다시 한 번 읽어보고 나서
어떻게 처리하면 좋을지 생각해보면 될 것 같습니다! -Step2-
질문이 있으면 언제든 디엠주세요!

2022-08-10 05:52 UTC, jaemuYeo commented on ios-baseball/ios-baseball/main.swift
> +func createRandomIntArray() -> [Int] {
create보다 generate는 어떻게 생각하시나요??🤔

Collection 타입 중 Array를 선택하여 구현하셨군요!!
코드에 고민한 티가 많이 납니다 👏
다만 조금 더 좋은 방법을 제시해드리고 싶어요
Swift의 Collection 타입 중 중복된 값이 배열에 존재할 수 없는 컬렉션 타입이 있답니다.
문서를 읽어보시고 한 번 활용해서 수정해볼 수 있을까요?

2022-08-10 05:52 UTC, jaemuYeo commented on ios-baseball/ios-baseball/main.swift
> +}
함수 사이의 개행은 해주시면 좋아요!
이유는 뭘까요??

2022-08-10 05:52 UTC, jaemuYeo commented on ios-baseball/ios-baseball/main.swift
> +        if !randomIntArray.contains(number){
if 문이 열리는 중괄호에 띄어쓰기가 되어있지 않군요!
이런 사소한 오타 하나하나도 중요하답니다 👍

2022-08-10 05:52 UTC, jaemuYeo commented on ios-baseball/ios-baseball/main.swift
> +    while randomIntArray.count < 3{
이 곳에도 while 문이 열리는 중괄호에 띄어쓰기가 안 되어 있군요!

2022-08-10 05:52 UTC, jaemuYeo commented on ios-baseball/ios-baseball/main.swift
> +    while(leftCnt>=1 && winOrLose == 0) {
코드는 통일성도 매우 중요합니다 ( 띄어쓰기, 개행 등등)
현재 비교연산자가 && 기준 왼쪽은 띄어쓰기가 안되어있고 오른쪽은 되어있어요!!
저는 오른쪽을 더 선호합니다 😀 이유가 뭘까요??

2022-08-10 05:52 UTC, jaemuYeo commented on ios-baseball/ios-baseball/main.swift
> +        var inputIntArr: [Int] = []
이 곳도 Step2에 있어야 할 변수와 그에 준하는 네이밍들이 보이는 것 같아요!

2022-08-10 05:52 UTC, jaemuYeo commented on ios-baseball/ios-baseball/main.swift
> +        let result: Dictionary<String, Int> = winOrLoseCheck(inputIntArr, randomIntArray)
딕셔너리를 통해 결과값을 표현하셨군요!! 좋은 시도예요 👍

2022-08-10 05:52 UTC, jaemuYeo commented on ios-baseball/ios-baseball/main.swift
> +        if leftCnt == 0{
띄어쓰기가 안되어있군요!

2022-08-10 05:52 UTC, jaemuYeo commented on ios-baseball/ios-baseball/main.swift
> +        print("\(result["s"]!) 스트라이크, \(result["b"]!) 볼")
딕셔너리의 키 값을 통해 값을 추출하려고 하는데 강제추출이 되고있어요 🤔
강제추출 말고 다른 방법은 어떨까요??
그리고 다른 사람이 코드를 보았을 때 키 값인 s와 b가 어떤 뜻인지 명확하게 알 수 있을까요??

2022-08-10 05:52 UTC, jaemuYeo commented on ios-baseball/ios-baseball/main.swift
> +func winOrLoseCheck(_ human: [Int],_ computer: [Int]) -> Dictionary<String, Int> {
스위프트 스타일 가이드의 네이밍 부분을 참고하여 함수의 네이밍을 한 번 더 고민해보면 좋겠습니다!

2022-08-10 05:52 UTC, jaemuYeo commented on ios-baseball/ios-baseball/main.swift
> +    var s_count: Int = 0
축약된 단어사용과 언더스코어보다는 카멜케이스를 활용하여 조금 더 명확하게 표현해주세요!!
너무 짧은 변수명도 가독성을 헤친답니다🥲

2022-08-10 05:52 UTC, jaemuYeo commented on ios-baseball/ios-baseball/main.swift
> +    for i in 0...2{
for문이 시작하는 중괄호에 띄어쓰기가 안되어있어요!
위의 변수들과 한 칸 정도 개행해주면 구분하기 훨씬 좋을 거같습니다 :)

2022-08-10 05:52 UTC, jaemuYeo commented on ios-baseball/ios-baseball/main.swift
> +    let dic: Dictionary<String, Int> = ["s": s_count, "b": b_count]
dic이란 네이밍도 명확했으면 좋곘습니다😉

2022-08-10 05:54 UTC, wormsJJG commented on ios-baseball/ios-baseball/main.swift
> +var menuNum: Int = 0
넵넵

2022-08-10 05:55 UTC, wormsJJG commented on ios-baseball/ios-baseball/main.swift
> +var leftCnt: Int = 9
시작 페이지에서 유저가 게임시작 또는 게임종료를 선택할때 번호로 입력받아 menuNum, 남은 횟수를 의미하는데 제가 작명 센스가 부족한가 봅니다 ㅠㅡㅠ 많이 노력해야겠습니다.

2022-08-10 05:56 UTC, wormsJJG commented on ios-baseball/ios-baseball/main.swift
> +func startMenu() {
넵넵

2022-08-10 05:56 UTC, wormsJJG commented on ios-baseball/ios-baseball/main.swift
> +    menuNum = Int(readLine()!)!
넵

2022-08-10 05:57 UTC, wormsJJG commented on ios-baseball/ios-baseball/main.swift
> +func createRandomIntArray() -> [Int] {
넵 문서를 다시 한번 정독하여 수정해보겠습니다.

2022-08-10 05:58 UTC, wormsJJG commented on ios-baseball/ios-baseball/main.swift
> +        print("\(result["s"]!) 스트라이크, \(result["b"]!) 볼")
방법을 좀더 강구해봐야겠네요, 네이밍도 신경써보겠습니다.

2022-08-10 05:59 UTC, wormsJJG commented on ios-baseball/ios-baseball/main.swift
> +func winOrLoseCheck(_ human: [Int],_ computer: [Int]) -> Dictionary<String, Int> {
넵

2022-08-10 05:59 UTC, wormsJJG commented on ios-baseball/ios-baseball/main.swift
> +    var s_count: Int = 0
네이밍에 많은 신경을 써야겠네요 ㅜㅡㅜ

2022-08-10 06:00 UTC, wormsJJG commented on ios-baseball/ios-baseball/main.swift
> +    for i in 0...2{
넵 실행해보겠습니다.

2022-08-10 06:00 UTC, wormsJJG commented on ios-baseball/ios-baseball/main.swift
> +    let dic: Dictionary<String, Int> = ["s": s_count, "b": b_count]
넵 ㅠㅠㅠ

2022-08-11 13:32 UTC, jaemuYeo requested changes
재근!! 쉬더라도 시간이 된다면 이번 프로젝트 끝까지 꼭 해보길 바래요🙏
재요청 하면서 순서도도 같이 넣어주었으면 좋았을텐데 아쉽습니다!!
PR을 보낼때는 항상 신중하게 무엇을 추가하면 좋을지 
고친부분에서 실수해서 놓친부분은 없는지 체크하고 절대로 급하게 보내지않길 바랍니다 😀

## 코드
<img width="195" alt="스크린샷 2022-08-11 오후 10 30 10" src="https://user-images.githubusercontent.com/70311145/184144849-59c99901-fa07-4116-9299-85b043858f25.png">
임의의 수가 다른데 모두 같은 볼과 스트라이크의 결과가 나오고있죠??
이거,, 정말 정말 치명적인 에러입니다!
고민해보고 찾아내서 수정해보세요💪
컴퓨터의 임의의수를 print문 찍어서 유저의 임의의 수와 비교해보며 구현해보시면 편합니다!

2022-08-11 13:32 UTC, jaemuYeo commented on ios-baseball/ios-baseball/main.swift
> +func menu() {
이 함수는 지금 사용되지 않는데 구현되어있네요 🤔

2022-08-11 13:32 UTC, jaemuYeo commented on ios-baseball/ios-baseball/main.swift
> +func menuNumberCheck(_ menuNumber: Int) {
이 함수도 지금 사용되지 않는군요 😭

2022-08-11 13:32 UTC, jaemuYeo commented on ios-baseball/ios-baseball/main.swift
> +//        let number = Int.random(in: 1...9)
전에도 남긴 코멘트지만 불필요한 주석은 정말정말 좋지 않아요,,!🔥

2022-08-11 13:32 UTC, jaemuYeo commented on ios-baseball/ios-baseball/main.swift
> +
불필요한 개행이라는 생각이 듭니다 :)

2022-08-11 13:32 UTC, jaemuYeo commented on ios-baseball/ios-baseball/main.swift
> +func gameStart() {
이 부분은 전에 코멘트 남긴 것이니 어느정도 힌트를 드릴게요!
함수의 네이밍을 할때는 동사가 가장 앞에 오는 것이 베스트입니다~
Swift 스타일 가이드 문서를 다시 한 번 확인해주세요! 정말정말 중요합니다!

2022-08-11 13:32 UTC, jaemuYeo commented on ios-baseball/ios-baseball/main.swift
> +        print("")
이렇게 코드로만 봤을때 감이 잡히지 않는 개행처리를 다른 방법으로 어떻게 처리할 수 있을까요?🤔

2022-08-11 13:32 UTC, jaemuYeo commented on ios-baseball/ios-baseball/main.swift
> +    while(remainingCount>=1) {
```swift
 while(remainingCount >= 1)
```
등호 앞뒤로는 띄어쓰기를 한 번 해주는게 가독성이 좋습니다!
아래 함수는 잘 해놨는데 여기만 안되어있네요! 통일성에 어긋납니다😲

2022-08-11 13:32 UTC, jaemuYeo commented on ios-baseball/ios-baseball/main.swift
> +func winLoseDicision(_ human: Set<Int>,_ computer: Set<Int>){
이 함수의 네이밍도 한 번 고려해보세요! 그리고 매개변수가 여러개일 때에는 쉼표 다음에 띄어쓰기를 한 번 하면 좋아요!!
중괄호도 붙어있네요 😀

2022-08-15 05:21 UTC, wormsJJG commented on ios-baseball/ios-baseball/main.swift
> +func menu() {
삭제하겠습니다!

2022-08-15 05:21 UTC, wormsJJG commented on ios-baseball/ios-baseball/main.swift
> +func menuNumberCheck(_ menuNumber: Int) {
삭제하겠습니다!

2022-08-15 05:21 UTC, wormsJJG commented on ios-baseball/ios-baseball/main.swift
> +//        let number = Int.random(in: 1...9)
넵

2022-08-15 05:21 UTC, wormsJJG commented on ios-baseball/ios-baseball/main.swift
> +
넵

2022-08-15 05:22 UTC, wormsJJG commented on ios-baseball/ios-baseball/main.swift
> +func gameStart() {
넵!

2022-08-15 05:23 UTC, wormsJJG commented on ios-baseball/ios-baseball/main.swift
> +    while(remainingCount>=1) {
앗 넵!

2022-08-15 05:25 UTC, wormsJJG commented on ios-baseball/ios-baseball/main.swift
> +func winLoseDicision(_ human: Set<Int>,_ computer: Set<Int>){
앞에서 주신 힌트와 비슷한 내용같네요 !

2022-08-15 05:26 UTC, wormsJJG commented on ios-baseball/ios-baseball/main.swift
> +        print("")
고민하고 해결해보겠습다.

2022-08-16 07:30 UTC, merged