[STEP 1] 도도
tasty-code/ios-baseball pull request #20
Opened 2022-08-11 13:33 UTC by dddowon

스위프트가 처음이라 자세하게 리뷰 부탁드립니다!

### **[STEP 1] 수행 내용**
flow chart 작성 후 README 파일에 추가
임의의 수 생성
사용자가 입력하는 수를 임의의 수로 비교

### **고민했던 점**
처음부터 순서도를 작성하는 것이 어려워 코딩을 하면서 순서도를 작성했습니다.
가이드라인을 아직 보면서 하기 좀 어려워서 안 지키면서 했던게 아쉬웠습니다.

### **궁금한 점**
스위프트 가이드라인을 어떤 식으로 보면 좋을지 궁금합니다.
ex ) 하나하나 해석하며 읽는다.

2022-08-12 02:57 UTC, jaemuYeo requested changes
도도~ 프로젝트 첫 PR 축하합니다 👍
Swift가 처음인데도 잘 해주었네요!! 멋집니다 ㅎㅎ
앞으로 달릴 코멘트는 제 말이 100프로 다 정답을 요구하는 것이 아니니 참고해주시고
도도의 코드에 대한 이유가 궁금해서 정말 질문만 하는 걸 수도있으니
모든 코멘트에 대해 수정하지 않으셔도 되지만
수정을 하지 않아도 되는 이유에 대해서도 같이 코멘트 남겨주시면 좋을 것 같아요 😀
추가로 너무 긴 고민은 자칫하면 힘들어질 수 있어요,, ㅠ_ㅠ
저나 타코캣이 상시대기중이니까 언제든 부르거나
의존모둠에게 말그대로 의존하면서 프로젝트를 진행하면
많이 위안되고 도움도 될거예요!!!
혼자만의 학습을 할거면 독학을 하지 여기서 공부할 필요가 없잖아요?? ㅎㅎㅎ
정말정말 부담 가지지말고 차근차근 해봅시다 💪

## 순서도
순서도의 작성이 어려우셨군요!!
순서도를 작성하는 이유는 뭘까요??
제 생각에는 코드를 작성하기전에 흐름에 대해 파악하기 위한 용도
또는 나의 코드를 이해할 수 있는 수단이라고 생각이 들어요!!
프로젝트의 요구사항과 실행예시등을 참고해서
꼭 컴퓨터로 먼저 작성하지 않고, 손으로 공책에 글처럼 (의사코드와 같은) 써내려 가보아도
많은 도움이 될거예요😀
현재 순서도는 제외된 몇 가지가 있는거 같아요
1. 사용자 입력(메뉴 선택, 숫자 입력)에 대한 에러처리
2. No카운트, 볼 카운트 이후에 흐름이 끊김
3. 스트라이크가 +1 되고 그 값이 3인지 판단
4. 스트라이크가 3일 경우 어떻게 되는지 실행 예시 참고
5. 시도횟수 차감에 대한 것이 없음
6. for문(반복문)을 판단하는 모형에 넣음 (반복문을 없애고 흐름선으로 반복을 표현해주세요)

## 코드
코드의 제일 중요한 것은 일단 정상적으로 실행되는가? 입니다 😁
실행을 시켜보니 실행예시와는 다른 결과가 나오는군요!! 😭
코드에 대한 코멘트는 해당 코드에 남겨놓겠습니다~~
1. 사용자 수가 배열에 감써져서 출력
2. 사용자 임의의 수가 세 개중 중복되는 숫자가 있음
3. 컴퓨터 승리 프린트 후에 남은 기회가 출력되어야함 (실행예시 이미지 참고)

## 질문
공식문서는 자주 볼수록 핵심 단어들을 빠르게 파악하는 능력이 생깁니다!
많이 힘들겠지만 정말정말 필수예요,,ㅎㅎ
가이드라인 이외에 developer도 앞으로 자주 보게 될텐대요,,
전부 영어랍니다 😭 번역기를 써서라도 꼭 훑어보세요!
가이드라인에서는 지금 당장 힘드시면 네이밍 부분이라도 꼭 정독하길 바래요🙏
위안 될지 모르겠지만 저도 아직까지 공식문서 읽는건 힘들답니다 ㅎㅎㅎ

2022-08-12 02:57 UTC, jaemuYeo commented on baseballgame/baseballgame/main.swift
> +
불필요한 개행이 이루어졌군요!

2022-08-12 02:57 UTC, jaemuYeo commented on baseballgame/baseballgame/main.swift
> +
여기 사이는 종류를 구분지어 놓은 건가요??
네이밍만 명확하면 꼭 개행을 하지 않아도 된답니다 😀

2022-08-12 02:57 UTC, jaemuYeo commented on baseballgame/baseballgame/main.swift
> +var overlapArray:Set<Int> = []
위아래로 타입명시할 때는 콜론(:) 다음 띄어쓰기를 했는데 여기는 안하셨네요!
```swift
var overlapArray: Set<Int>
```
띄어쓰는 이유는 가독성 측면에서 하는 것이고 위아래와 또는 전체코드에 대해 통일성을 지키는 것이 좋습니다!🙂

2022-08-12 02:57 UTC, jaemuYeo commented on baseballgame/baseballgame/main.swift
> +var input_numbers: [Int] = []
Swift는 네이밍할때 단어 사이에 언더스코어를 넣기보다는 CamelCase를 활용하라고 제시합니다.
그 중에서도 lowerCamelCase와 UpperCamelCase 두 종류가 있는대요?
어느 곳에서 lower를 사용하고 어느곳에서 upper를 사용할까요?
아래 스트라이크 카운트와 볼카운트도 포함하여 코멘트 남깁니다!

2022-08-12 02:57 UTC, jaemuYeo commented on baseballgame/baseballgame/main.swift
> +func comparison(){
함수의 네이밍이 명확하지 않은 것 같아요!
[swift design guideline](https://www.swift.org/documentation/api-design-guidelines/)의 네이밍 부분을 참고하여 다시한번 고민해보시면 될 것 같아요!!
어려우시면 디엠주세요 ~~

2022-08-12 02:57 UTC, jaemuYeo commented on baseballgame/baseballgame/main.swift
> +    for index in 0...2{
중괄호를 열때에 띄어쓰기를 한 번해주면 좋아요!
아래의 while문 내부는 전부 띄어쓰기를 적용해주었는데
이 곳에는 안되어있군요 😉

2022-08-12 02:57 UTC, jaemuYeo commented on baseballgame/baseballgame/main.swift
> +var attempt = 9
시도라는 단어보다는 기회 또는 남은 횟수, 남은 기회 등이 좋을 것 같습니다!
도도 생각은 어떄요?

2022-08-12 02:57 UTC, jaemuYeo commented on baseballgame/baseballgame/main.swift
> +var randomArray: [Int] = []
여기 두 배열에 대한 네이밍은 유저와 컴퓨터의 숫자가 들어갈텐데 거기에 맞게 네이밍지어보면 어떨까요?
다른 사람이 코드를 보았을때는 어떤 값이 들어가는지 이해하기 힘들 것 같아요🤔

2022-08-12 02:57 UTC, jaemuYeo commented on baseballgame/baseballgame/main.swift
> +while overlapArray.count < 3 {
여기부터 마지막까지의 함수들도 기능별로 나누어서 함수에 담아볼 수 있을까요?

2022-08-12 02:57 UTC, jaemuYeo commented on baseballgame/baseballgame/main.swift
> +    print("임의의 수 : \(input_numbers)")
이 값이 출력된 결과가 실행 예시와 다르게 배열에 감싸진 모습이예요!!
숫자만으로 출력되게 해볼까요??

2022-08-12 02:57 UTC, jaemuYeo commented on baseballgame/baseballgame/main.swift
> +randomArray = Array<Int>(overlapArray)
이런 경우
```swift
randomArray = Array(overlapArray)
```
타입 명시 없이 이렇게 형변환 해주셔도 됩니다!

2022-08-12 02:57 UTC, jaemuYeo commented on baseballgame/baseballgame/main.swift
> +for _ in 1...9 {
Loop안에 Loop가 한 번 중첩(들여쓰기) 되었네요!
프로젝트 제약사항에 들여쓰기는 금지됩니다!
해당 제약이 생긴 이유와 해결방법에 대해 알아보면 좋을 것 같아요 🙂

2022-08-12 02:57 UTC, jaemuYeo commented on baseballgame/baseballgame/main.swift
> +    attempt-=1
등호 사이에는 
```swift
attempt -= 1
```
앞뒤로 띄어쓰기해주면 가독성이 좋습니다 👍

2022-08-12 05:53 UTC, dddowon commented on baseballgame/baseballgame/main.swift
> +var attempt = 9
시도...보다는 기회가 좋은 거 같아요!

2022-08-12 05:57 UTC, dddowon commented on baseballgame/baseballgame/main.swift
> +var randomArray: [Int] = []
다른 사람이 보았을 때도 한눈에 알아볼 수 있게 짓는 게 좋은 거 같아요!

2022-08-13 07:50 UTC, jaemuYeo requested changes
코드와 순서도 모두 빠르게 수정해주었군요! 👍
이번 프로젝트의 마지막 리뷰가 될 것 같아요~
이번에 남긴 코멘트를 통해 적용할 부분이 있으면 복습차 진행해보면 좋을 거같아요 😀

## 순서도
전과 비교했을때 너무 좋게 개선된것 같아요!!
다만 아직 실행예시와 다른 부분은 사용자 또는 컴퓨터 승리 후 게임이 종료되지 않는다는 거예요~
실행예시를 다시한번 살펴보면 좋을 것 같습니다 😀

코드의 실형결과는 예시와 알맞게 구현된 것같아요! 👍

2022-08-13 07:50 UTC, jaemuYeo commented on baseballgame/baseballgame/main.swift
> +var computerSetNumbers: Set<Int> = []
이 친구는 한 곳의 함수에서만 사용되고 있어요
전역변수와 지역변수중 어떤 곳에 두면 좋을까요?

2022-08-13 07:50 UTC, jaemuYeo commented on baseballgame/baseballgame/main.swift
> +func makeCoputerNums() {
네이밍이 간략해지는 것보다는 Nums라는 표현보다 Numbers라는 명확한 네이밍이 더 좋을 것같아요!

2022-08-13 07:50 UTC, jaemuYeo commented on baseballgame/baseballgame/main.swift
> +func comparisonNumbers() {
comparison 보다는 compairWith 또는 compair가 좋은 것 같습니다

2022-08-13 07:50 UTC, jaemuYeo commented on baseballgame/baseballgame/main.swift
> +        if userNumbers[index] == computerNumbers[index]{
이 곳에 중괄호들이 띄어쓰기가 이루어지지 않았네요!

2022-08-13 07:50 UTC, jaemuYeo commented on baseballgame/baseballgame/main.swift
> +func gameStart() {
gameStart보다는 startGame이 네이밍이 더 적합할 것 같습니다 😀

2022-08-16 07:35 UTC, closed without merging