[STEP 1] Ireu
tasty-code/ios-baseball pull request #6
Opened 2022-08-09 07:19 UTC by Y00ujin

### @jaemuYeo 리뷰 부탁드려요 🙇🏻‍♂️

<br>
<br>

### [STEP 1] 수행한 내용
- #### README.md FlowChart 추가
- #### 임의의 수 생성 함수 `createRandomNumber()` 추가
- #### 볼과 스트라이크 결과를 반환하는 함수 `compareCorrectNumber()` 추가
- #### 게임 시작 함수 `startGame()` 추가

2022-08-09 09:07 UTC, jaemuYeo requested changes
이루 프로젝트 첫 PR 고생하셨습니다!! 👏🎉
커밋 컨벤션도 잘 지켜주셨군요 👍
순서도와 코드에 대한 몇 가지 코멘트 남겨놓겠습니다!!

## 순서도
전반적으로 너무 잘 작성해주었어요 👏
그래도 조금은 아쉬운 부분이 남아 코멘트 남기는 것이니 너무 아쉬워마요!!
1. 흐름선의 모호함
흐름선이라고 하면 보통 -> 처럼 화살표를 가리키고 있어
어디서 어디로 가는지 명확하게 표시해주어야 한답니다.
다만 이루가 작성하신 FlowChart를 보면 화설표가 표시되지 않아
아래에서 위로가는지 위에서 아래로 가는지 구분하기 힘든점이 있어요!

2. 추가되었으면 하는 부분
남은 기회 (9회)가 언제 생성이 되고 언제 차감되어 0이 되기까지의
과정이 빠진 것 같아요!!
고민해보시고 추가하면 좋을 것 같아요 😉

그 외에는 너무 멋지게 해주었어요!!

## 코드

Step1의 실행예시와 다른 점이 있어요!!
배열로 감싸진 임의의 수를 벗겨내어 출력되고있습니다
실행예시에 맞게 Try 해보세요!!💪

그 외 부분은 코드에 코멘트 달아두겠습니다!
은닉화에 대한 부분은 뒤에 다룰 내용이니 지금은 적용하지 않으셔도 됩니다!
당분간은 넣어두세요 ㅎㅎ

2022-08-09 09:07 UTC, jaemuYeo commented on BaseBall/BaseBall/main.swift
> +private func createRandomNumber() -> [Int]{
공식문서에서  또는 대부분 코드 스타일은 중괄호를 한 칸 띄어쓴답니다!
그 스타일에 맞춰야하는 이유와 띄어쓰는 이유는 무엇일까요?🤔
(아래 코드 모두 포함입니다!)

2022-08-09 09:07 UTC, jaemuYeo commented on BaseBall/BaseBall/main.swift
> +// MARK: - 임의의 수 생성 함수
마크 주석과 일반 주석의 차이는 무엇인가요??
각각은 어떤 경우에 사용될까요?
만약 코드가 읽기 쉽고 네이밍이 명확하다면 주석이 필요할까요?

2022-08-09 09:07 UTC, jaemuYeo commented on BaseBall/BaseBall/main.swift
> +    var randomNumber = [Int.random(in: 1...3), Int.random(in: 4...6), Int.random(in: 7...9)]
중복된 값을 넣지 않기 위해 구현하셨군요!!
Swift Collection타입 중 중복된 값을 넣지 않는 컬렉션은 무엇일까요?
해당하는 Collection 타입으로 구현해보는건 어때요??😀

2022-08-09 09:07 UTC, jaemuYeo commented on BaseBall/BaseBall/main.swift
> +        }else if correctNumber.contains(number[i]){
contains 메서드를 적절하게 사용해주었네요 👍
중괄호 안과 밖은 한 칸의 띄어쓰기해주면 좋아요!
위 코멘트와 비슷한 내용입니다~

2022-08-09 09:07 UTC, jaemuYeo commented on BaseBall/BaseBall/main.swift
> +    print("정답 \(correctNumber)")
이 print문은 요구사항에 없는 내용입니다 🤗

2022-08-10 01:01 UTC, Y00ujin commented on BaseBall/BaseBall/main.swift
> +    print("정답 \(correctNumber)")
앗 제거하였습니다! 😦

2022-08-10 01:23 UTC, Y00ujin commented on BaseBall/BaseBall/main.swift
> +// MARK: - 임의의 수 생성 함수
일반 주석은 해당 코드가 어떤 코드인지 이해하기 쉽게하는 역할을 합니다. 
마크 주석도 그 목적은 동일하지만 실선을 생성하여 코드의 가독성을 높이는 것 뿐만 아니라 실선을 통한 구역설정이 가능하여 기능 구분의 역할도 수행할 수 있습니다.

또 마크 주석을  가진 프로퍼티나 메소드는 Xcode 상단의 경로 바에서 마크 주석을 가지지 않은 프로퍼티나 메소드와 구분되게 실선, 볼드체가 적용되어 보다 쉽게 확인이 가능하며 해당 프로퍼티나 메소드로 빠르게 이동할 수 있습니다.

따라서 구역 설정이 필요하지 않은 간단하지만 주석이 필요한 코드에는 일반 주석을 사용하고, 코드의 내용이 비교적 방대하여 구역 설정 또한 필요하다고 판단되면 마크 주석을 사용하면 좋을 것 같습니다! 🫡

코드가 읽기 쉽고 네이밍이 명확하다면 굳이 주석으로 설명을 덧붙이지 않아도 될 듯 합니다!
주석은 나쁜 코드를 보완하지 못한다. 라는 Clean Code 책의 말을 기억하며 최대한 네이밍에 신경쓴 후 네이밍이 명확하여 코드가 읽기 쉽다면 주석을 최대한 줄이는 습관을 들여보겠습니다. 🥳


**참고자료**
https://nesoy.github.io/articles/2018-01/CleanCode-Comment
https://an-onymous.tistory.com/entry/Swift-MARK-%EB%82%98%EB%A7%8C%EC%9D%98-%EC%A3%BC%EC%84%9D%EC%9C%BC%EB%A1%9C-%EC%BD%94%EB%93%9C-%EA%B5%AC%EC%97%AD%EC%84%A4%EC%A0%95%ED%95%98%EA%B8%B0
https://jaelight.tistory.com/18

2022-08-10 01:25 UTC, Y00ujin commented on BaseBall/BaseBall/main.swift
> +    var randomNumber = [Int.random(in: 1...3), Int.random(in: 4...6), Int.random(in: 7...9)]
Set 컬렉션 타입을 사용하여 구현해보겠습니다!
새로운 구현 방법 감사합니다 !! 🥳🎉

2022-08-10 01:31 UTC, Y00ujin commented on BaseBall/BaseBall/main.swift
> +        }else if correctNumber.contains(number[i]){
이렇게 띄어쓰기 하는 것을 말씀하시는 걸까요?? ...😮

2022-08-10 01:31 UTC, Y00ujin commented on BaseBall/BaseBall/main.swift
> +private func createRandomNumber() -> [Int]{
찾아봐도 명확한 자료가 나오지 않아 그냥 제 생각을 말씀드릴게요..!! 😭
반환 타입이 있다면 반환 타입의 가독성을 위한 것이거나, 반환 타입이 없다면 함수의 이름을 보기 편하게 하기 위해서 라고 생각합니다!

2022-08-10 02:31 UTC, jaemuYeo commented on BaseBall/BaseBall/main.swift
> +private func createRandomNumber() -> [Int]{
좋아요!! 👍 가독성 측면에서 좋고 많은 사람들이 띄어쓰기를 하기때문에 통일성을 갖추기 위함입니다!
```swift
func createRandomNumber() -> [Int] { // <- 중괄호와 반환타입 사이의 띄어쓰기 

}
```
처럼 모든 중괄호에는 띄어쓰기를 해주시는게 좋아요 !

2022-08-10 02:35 UTC, Y00ujin commented on BaseBall/BaseBall/main.swift
> +private func createRandomNumber() -> [Int]{
넵!! 알겠습니다!

2022-08-10 02:35 UTC, jaemuYeo commented on BaseBall/BaseBall/main.swift
> +// MARK: - 임의의 수 생성 함수
와우 ,, 엄청 열심히 조사하셨군요!! 최곱니다 👏👏👏
조사하신 내용 처럼 아직까지는 주석이 필요하다고 느껴지지 않아요!!
코드에 대한 설명이 혹시나 필요하다면 README나 PR 내용에 추가해주셔도 좋습니다 ㅎㅎ

2022-08-10 02:36 UTC, jaemuYeo commented on BaseBall/BaseBall/main.swift
> +        }else if correctNumber.contains(number[i]){
Swift 언어 공식문서에 있는 코드들을 복사 붙여넣기해서 관찰해보면 좋을거같아요!

2022-08-10 03:11 UTC, Y00ujin commented on BaseBall/BaseBall/main.swift
> +// MARK: - 임의의 수 생성 함수
네! 알겠습니다 👍🏻

2022-08-10 03:11 UTC, Y00ujin commented on BaseBall/BaseBall/main.swift
> +        }else if correctNumber.contains(number[i]){
네! 확인하고 수정해보겠습니다 👍🏻

2022-08-10 08:20 UTC, jaemuYeo requested changes
빠르게 수정해주셨네요!! 👍

## 순서도
전보다는 훨씬 흐름이 좋아진 것 같습니다!
다만 입력에 대한 에러처리에서
메뉴를 선택하는 입력과 숫자 세 개를 입력하는 것에 대한 에러처리가
다르게 출력되고 있는 것을 실행예시에서 확인할 수 있어요!!
그 부분에 대한 수정이 이루어지면 좋을 것 같습니다 :)

## 코드
전체적으로 코드 컨벤션이 많이 개선되었군요! 👏
실행예시와 다르게 출력되고있어요!
뭐가 빠졌는지 다시 한 번 실행예시를 꼼꼼히 살펴보고 추가해주시면 될 것 같습니다!
그 외에는 코드에 코멘트 남겨놓을게요!

2022-08-10 08:20 UTC, jaemuYeo commented on BaseBall/BaseBall/main.swift
> +        randomNumber = Array(Set(randomNumber))
Set을 사용해보니 어때요??
전체적으로 Set을 활용하지 않고 Array를 Set으로 형변환 하여 사용하신 이유가 궁금합니다!!
Set의 특징으로는 어떤 것들이 있을까요??

2022-08-10 08:20 UTC, jaemuYeo commented on BaseBall/BaseBall/main.swift
> +        }else if correctNumber.contains(number[i]) {
이 곳에도 띄어쓰기가 빠진 것 같네요!

2022-08-10 08:20 UTC, jaemuYeo commented on BaseBall/BaseBall/main.swift
> +    for i in 0...2 {
for 문안에 if 문을 통해 들여쓰기가 발생했군요!!
프로젝트의 `이번 과제 수행시 제약사항`을 확인 후
프로젝트 실습란에 `들여쓰기에 관하여`란 부분을 읽어보고
어떻게 개선하면 좋을지 왜 이런 제약을 걸었는지에 대해 고민해보고 수정해볼까요??🤔

2022-08-10 08:20 UTC, jaemuYeo commented on BaseBall/BaseBall/main.swift
> +        print("임의의 수 : \(randomNumber.map{ String($0) }.joined(separator: " "))")
map의 활용을 적절하게 해주었네요 멋져요 👏

2022-08-11 00:56 UTC, Y00ujin commented on BaseBall/BaseBall/main.swift
> +        randomNumber = Array(Set(randomNumber))
Set을 사용하니 중복된 수를 따로 제거하지 않아도 돼서 편리했어요!

compareCorrectNumber() 함수 내부에서 정답과 사용자가 입력한 값을 비교해야 하는데, 이때 숫자의 순서가 중요하게 작용하여 Array를 사용해야 했어요. 그래서 임의의 수를 생성할 때에만 Set을 사용하여 중복을 제거했습니다.

Set은 순서가 없는 중복을 허용하지 않는 컬렉션 타입으로 순서가 중요하지 않거나 중복 없이 하나의 항목을 가져야 할 때 사용합니다. 또 Set을 사용하면 합집합이나 교집합 등 집합 연산을 사용할 수 있습니다.


**참고자료**
- http://minsone.github.io/mac/ios/swift-set-type
- https://developer.apple.com/documentation/swift/set

2022-08-11 00:57 UTC, Y00ujin commented on BaseBall/BaseBall/main.swift
> +        }else if correctNumber.contains(number[i]) {
넵! 수정했습니다 🙇🏻‍♂️👍🏻

2022-08-11 00:57 UTC, Y00ujin commented on BaseBall/BaseBall/main.swift
> +        print("임의의 수 : \(randomNumber.map{ String($0) }.joined(separator: " "))")
ㅎㅎ 감사합니다! 🥳🎉

2022-08-11 01:34 UTC, Y00ujin commented on BaseBall/BaseBall/main.swift
> +    for i in 0...2 {
ballCount는 두 집합의 교집합으로 구현하여 들여쓰기를 제거했어요! 

strikeCount도 두 집합의 교집합을 구해서 서로의 Array의 index가(순서) 같은지 비교하려고 했는데, 그렇게 하면 너무 구현 방식이 복잡해져서 또 다른 구현 방식이 있을까요? 😭

2022-08-11 06:06 UTC, jaemuYeo commented on BaseBall/BaseBall/main.swift
> +    for i in 0...2 {
이 부분은 들여쓰기가 아닌데 제가 실수한 거같아요 >< 
보통 하나의 함수에 하나의 기능만 할 수 있도록 `기능 분리` 목적으로
들여쓰기 금지에 대한 제약을 준 것이기때문에 
for문 내부의 if문을 하나의 함수로 빼서 for문 내부에 함수 호출을 하면 들여쓰기에 대한 부분은 해결 될 것 같아요😀
지금 수정하신 방법도 좋습니다!!

2022-08-11 06:17 UTC, jaemuYeo reviewed
스텝1 고생하셨습니다 이루!! 👍
순서도도 잘 작성해주었네요 👏
이번 스텝은 여기서 머지 진행하겠습니다!!
코멘트에 남겨놓은 부분에서 수정이 필요한 부분이 있다면 마무리하고
다음 스텝 하면 될 거같아요!!
- 다음 스텝은 새로운 브랜치를 만들어 진행해보세요!⭐️

2022-08-11 06:17 UTC, jaemuYeo commented on BaseBall/BaseBall/main.swift
> +var tryCount = 9
한 곳의 함수에서만 사용된다면 전역변수말고 지역변수는 어떤가요?
전역변수와 지역변수의 차이, 각각의 장단점들을 조사해보면 좋을 것 같습니다 😉

2022-08-11 06:17 UTC, jaemuYeo commented on BaseBall/BaseBall/main.swift
> +        if number[i] == correctNumber[i] { strikeCount += 1 }
```swift
if number[i] == correctNumber[i] {
    strikeCount += 1
}
```
중괄호가 열리고 닫히는 부분은 이런식으로 개행해주는게 좋을 것 같아요
엄청 필수는 아니지만 당분간은 이렇게 진행해주세요!
너무 축약된 표현 또는 개행, 띄어쓰기 생략 등은 가독성에 많이 헤롭습니다~

2022-08-11 06:17 UTC, jaemuYeo commented on BaseBall/BaseBall/main.swift
> +    while tryCount > 0 {
여기 while 문도 따로 하나의 함수로 만들어서
startGame 내부에는 함수호출로만 이루어질 수 있게하면 좋을 것 같아요 😀

2022-08-11 06:17 UTC, jaemuYeo commented on BaseBall/BaseBall/main.swift
> +        if checkExistWinner(tryCount: tryCount, randomNumber: randomNumber) { break }
여기 개행부분도 위 코멘트와 같은 맥락입니다!

2022-08-11 06:17 UTC, merged