[step]1 rookie
tasty-code/ios-baseball pull request #9
Opened 2022-08-09 16:33 UTC by chaeyoon1101

@jaemuYeo 리뷰 잘 부탁드립니다

### 기능 구현
- FlowChart 추가
- 임의의 수 생성 함수 구현
- playGame 함수 구현

<br>
### 고민한 점, 궁금한 점

```swift
//임의의 수 생성 함수
func makeRandomNumber() -> Array<Int> {
    var arr: Array<Int> = []
    
    for _ in 0...2 {
        var randomNum = Int.random(in: 1...9)
        while arr.contains(randomNum) == true {
            randomNum = Int.random(in: 1...9)
        }
        arr.append(randomNum)
    }
    
    return arr
}
```

임의의 수를 생성하는 방법을 `randomNum`에 `Int.random()`을 사용하여 랜덤한 숫자를 담은 뒤 중복 체크를 한 후 중복 되는 수가 있다면 `randomNum`에 다시 새로운 랜덤한 숫자를 담는 방법을 사용했습니다
하지만 만약 `Int.random()`함수가 게속 같은 숫자를 가져온다면 무한루프에 걸리거나 오랜 시간이 걸릴 수도 있어 고민을 했습니다
어떻게 해결하는 방법이 있을까요

2022-08-10 02:10 UTC, jaemuYeo requested changes
루키 프로젝트 첫 PR 축하합니다!! 👏
빠르게 진행해주었군요 👍
순서도에 대한 부분과 질문 주신 내용은 이 곳을 통해 코멘트 남겨놓고
코드에 대한 부분은 해당 코드에 코멘트 남기겠습니다!
'앞으로 있을 리뷰에 대한 내용은 100% 내 말이 정답이니 그렇게 바꿔라'가 아니라
정말 코드를 짠 이유에 대해 궁금해서 물어보는 것도 있고,
제 의견에 대해 반감이 있으면 그 이유에 대해 남겨주셔도 좋습니다!!😀

## 질문에 대한 답변
Swift 컬렉션 타입에는 중복된 값을 넣지 않는 컬렉션 타입도 있답니다!
무엇일까요?? [Swift Collection타입](https://docs.swift.org/swift-book/LanguageGuide/CollectionTypes.html) 문서를 보며 해당 타입이 무엇인지 확인해보고
적용해보면 코드가 더 줄어들거 같아요 🤔
- Array로 구현한다고 무한루프에 빠질 가능성은 희박하다고 생각합니다!

## 순서도
<img width="163" alt="스크린샷 2022-08-10 오전 10 27 47" src="https://user-images.githubusercontent.com/70311145/183790416-a73c2f5e-22af-4150-9931-519bd2f5369c.png">
판단을 표시하는 모형에 반복문으로 작성해주셨군요!!
그 이유가 있나요??

<img width="103" alt="스크린샷 2022-08-10 오전 10 48 02" src="https://user-images.githubusercontent.com/70311145/183792561-c32b4d2e-bb99-424f-9ca0-951419c50fda.png">
오타인가용?? 🤔

전반적인 흐름은 좋지만 `for i in 0...2`에 대한 부분과
`컴퓨터 승리`, `사용자 승리` 이 외 print 되는 것들은 표현해주지 않은 것이 아쉽네요!
흐름도를 그려보도록 한 것은 정말로 작게 나누어  코드를 작성하기전에
결과물이 나오기까지의 흐름을 파악하기 위함입니다!! 한 번 더 Try 해보시면 좋을 거 같아요 🔥

2022-08-10 02:10 UTC, jaemuYeo commented on main/main/main.swift
> +func makeRandomNumber() -> Array<Int> {
해당 부분은 위에 남겨놓은 질문에 대한 답변을 통해 수정해보면 좋을거같아요 😀

2022-08-10 02:10 UTC, jaemuYeo commented on main/main/main.swift
> +let randomNumber = makeRandomNumber()
여기 전역변수 두 개를 아래에 작성하신 이유가 있나요??

2022-08-10 02:10 UTC, jaemuYeo commented on main/main/main.swift
> +    playGame()
재귀함수를 적절하게 사용해주셨군요 👏
Loop를 사용하지 않고 재귀로 구현하신 이유가 궁금해요!

2022-08-10 02:10 UTC, jaemuYeo commented on main/main/main.swift
> +func playGame() {
함수 로직에 대한 부분은 정말 잘 구현해주었어요 👏
다만 아쉬운 것은 이 `playGame`함수가 하는 일이 최소한 두 개 이상은 되어보입니다!!
조금 더 기능분리를 해 볼 수 있을까요??

2022-08-10 03:31 UTC, chaeyoon1101 commented on main/main/main.swift
> +func makeRandomNumber() -> Array<Int> {
넵 수정해보겠습니다

2022-08-10 03:32 UTC, chaeyoon1101 commented on main/main/main.swift
> +let randomNumber = makeRandomNumber()
큰 이유는 없었습니다 코드를 수정하다보니 아래에 적었던것 같아요

2022-08-10 03:32 UTC, chaeyoon1101 commented on main/main/main.swift
> +    playGame()
처음에는 재귀함수로 구현하려 했지만 STEP2 진행하면서 Loop로 다시 구현하게 되었습니다

2022-08-10 03:32 UTC, chaeyoon1101 commented on main/main/main.swift
> +func playGame() {
네 노력해보겠습니다

2022-08-11 01:02 UTC, jaemuYeo commented on main/main/main.swift
> +let randomNumber = makeRandomNumber()
오우!! 이유가 없는 코드는 안돼요 !! 🙅‍♂️
[선언](https://docs.swift.org/swift-book/ReferenceManual/Declarations.html)부분을 한 번 읽어보길 추천드려요!

2022-08-11 01:02 UTC, jaemuYeo commented on main/main/main.swift
> +    playGame()
이 부분은 스텝2에서 수정해주세요!

2022-08-11 08:41 UTC, jaemuYeo requested changes
리뷰반영하시느라 고생하셨습니다 👏
순서도도 훨씬 흐림이 좋아진 것 같아요 !!
다만 for문에 대한 처리는 판단(조건문)을 통해 흐름선으로 반복되는 곳을 가리키면
훨씬 더 좋을 것 같다는 생각이 듭니다! 루키는 어떻게 생각하시나요?🤔
코드에 대한 부분은 코드 각각 코멘트 남길게요~~
몇 개없으니 수정할 부분 있으면 수정하고, 다시 재요청주시면 머지진행할게요!

2022-08-11 08:41 UTC, jaemuYeo commented on main/main/main.swift
> +let randomNumber: Array<Int> = makeRandomNumber()
이 전역변수는 한 곳의 함수에서만 사용되는데 전역변수로 생성한 이유가 있나요??
전역변수와 지역변수의 차이에 대해 알아보고 각각의 특징에 대해 한 번 알아보면 좋을 것 같아요!

2022-08-11 08:41 UTC, jaemuYeo commented on main/main/main.swift
> +    var set: Set<Int> = []
set이라는 네이밍보다는 조금 더 명확한걸로 수정해보면 어떨까요?

2022-08-11 08:41 UTC, jaemuYeo commented on main/main/main.swift
> +func isGameEnd() -> Bool {
아~~ 이런 기능 분리 너무 좋아요!! 네이밍도 Bool타입 반환에 맞게 적절하게 해주셨네요! 👍

2022-08-11 08:41 UTC, jaemuYeo commented on main/main/main.swift
> +    strike = 0
애초에 전역변수로 0을 할당했는데 여기서 또 0을 할당했군요!? 🤔

2022-08-11 10:01 UTC, chaeyoon1101 commented on main/main/main.swift
> +let randomNumber: Array<Int> = makeRandomNumber()
`randomNumber`가 사용되는 함수인 `checkStrikeOrBall`함수 안에 `randomNumber`를 선언하게 된다면 `checkStrikeOrBall`함수를 호출하는 `playGame`함수가 반복되는 동안 계속 재선언 되기떄문에 프로그램이 실행되는 젤 처음 전역변수로 선언하려고 했습니다

2022-08-11 10:01 UTC, chaeyoon1101 commented on main/main/main.swift
> +    var set: Set<Int> = []
넵 명확한 네이밍으로 다시 수정해보겠습니다

2022-08-11 10:01 UTC, chaeyoon1101 commented on main/main/main.swift
> +func isGameEnd() -> Bool {
감사합니다!!

2022-08-11 10:01 UTC, chaeyoon1101 commented on main/main/main.swift
> +    strike = 0
`playGame`함수가 반복되면서 `strike`와 `ball` 변수가 0으로 초기화 되야 하기 때문에 다시 초기화를 했었습니다

2022-08-12 05:07 UTC, closed without merging